-- Step 1: Create 'ReqPlan' schema
CREATE SCHEMA ReqPlan
GO

-- Step 2: Create a view 'EcoResProductSystemLanguage' on 'ReqPlan' schema
CREATE VIEW [REQPLAN].[ECORESPRODUCTSYSTEMLANGUAGE] AS     
SELECT T1.RECID AS PRODUCT, T1.PARTITION AS PARTITION, T1.RECID AS RECID    
, T2.SYSTEMLANGUAGEID AS SYSTEMLANGUAGEID, T2.PARTITION AS PARTITION#2     
FROM ECORESPRODUCT T1     
CROSS JOIN SYSTEMPARAMETERS T2     
WHERE( T1.PARTITION  =  T2.PARTITION)
GO

-- Step 3: Create a view 'ReqPlannedOrderEntity' on 'ReqPlan' schema
CREATE VIEW [ReqPlan].[REQPLANNEDORDERENTITY] 
AS SELECT RE.MEMBERNAME AS PLANNEDORDERTYPENAME,
T1.COSTAMOUNT AS COSTAMOUNT, 
T1.DATAAREAID AS DATAAREAID,
T1.ITEMID AS ITEMNUMBER,
T1.QTY AS REQUIREMENTQUANTITY, 
T1.REFID AS PLANNEDORDERNUMBER, T1.REFTYPE AS PLANNEDORDERTYPE, T1.REQDATE AS REQUIREMENTDATE,  
T1.ITEMBOMID AS BOMID, T1.PLANNINGPRIORITY AS PLANNINGPRIORITY, T1.MODIFIEDDATETIME AS MODIFIEDDATETIME,
T4.DISPLAYPRODUCTNUMBER AS PRODUCTNUMBER,
T4.SEARCHNAME AS PRODUCTSEARCHNAME, 
T5.REQPLANID AS REQUIREMENTPLANID, T5.PLANTYPE AS REQUIREMENTPLANTYPE, T5.NAME AS REQUIREMENTPLANDESCRIPTION,   
T7.DESCRIPTION AS PRODUCTDESCRIPTION, CAST(NULL AS NVARCHAR(10))  AS PRODUCTVERSIONID 
FROM REQPO T1 
CROSS JOIN REQPLANVERSION T2 
CROSS JOIN INVENTDIM T3 
CROSS JOIN ECORESPRODUCT T4 
CROSS JOIN REQPLAN T5 
LEFT OUTER JOIN [ReqPlan].ECORESPRODUCTSYSTEMLANGUAGE T6 
ON(( T4.RECID  =  T6.PRODUCT)  
AND ( T4.PARTITION  =  T6.PARTITION)) 
LEFT OUTER JOIN ECORESPRODUCTTRANSLATION T7 
ON((( T4.RECID  =  T7.PRODUCT)  
AND ( T4.PARTITION  =  T7.PARTITION))
AND (( T6.SYSTEMLANGUAGEID  =  T7.LANGUAGEID)  
AND ( T6.PARTITION  =  T7.PARTITION))) 
JOIN RETAILENUMVALUETABLE RE
ON (RE.VALUE = T1.REFTYPE
AND RE.ENUMNAME = 'ReqRefType')
WHERE((((( T2.ACTIVE  =  1)  
AND (( T1.PLANVERSION  =  T2.RECID)  
AND ( T1.PARTITION  =  T2.PARTITION)))  
AND ((( T2.REQPLANID  =  T5.REQPLANID)  
AND ( T2.PARTITION  =  T5.PARTITION))  
AND (( T2.REQPLANDATAAREAID  =  T5.DATAAREAID)  
AND ( T2.PARTITION  =  T5.PARTITION))))  
AND ((( T1.COVINVENTDIMID  =  T3.INVENTDIMID)  
AND ( T1.DATAAREAID  =  T3.DATAAREAID))  
AND ( T1.PARTITION  =  T3.PARTITION)))  
AND (( T1.PRODUCT  =  T4.RECID)  
AND ( T1.PARTITION  =  T4.PARTITION)))
GO
