/**
 * SAMPLE CODE NOTICE
 * 
 * THIS SAMPLE CODE IS MADE AVAILABLE AS IS.  MICROSOFT MAKES NO WARRANTIES, WHETHER EXPRESS OR IMPLIED,
 * OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY OR COMPLETENESS OF RESPONSES, OF RESULTS, OR CONDITIONS OF MERCHANTABILITY.
 * THE ENTIRE RISK OF THE USE OR THE RESULTS FROM THE USE OF THIS SAMPLE CODE REMAINS WITH THE USER.
 * NO TECHNICAL SUPPORT IS PROVIDED.  YOU MAY NOT DISTRIBUTE THIS CODE UNLESS YOU HAVE A LICENSE AGREEMENT WITH MICROSOFT THAT ALLOWS YOU TO DO SO.
 */
 


import * as React from 'react';

import { ICaptchaData } from './captcha.data';
import { ICaptchaProps } from './captcha.props.autogenerated';
import { IVisibilityObserverProps } from '../../common/with-visibility-observer';
import { IModuleStateProps, withModuleState } from '@msdyn365-commerce-modules/checkout-utilities';

export interface ICaptchaViewProps extends ICaptchaProps<ICaptchaData>, IModuleStateProps, IVisibilityObserverProps {}
/**
 *
 * Captcha component
 * @extends {React.PureComponent<ICaptchaViewProps>}
 */
// @ts-expect-error
@withModuleState
class Captcha extends React.PureComponent<ICaptchaViewProps> {
    public async componentDidMount(): Promise<void> {
        this._initModuleState();
        this.props.moduleState.onPending();
    }

    public render(): JSX.Element | null {
        return this.props.renderView(this.props);
    }

    /**
     * Initialize module state.
     */
    private readonly _initModuleState = (): void => {
        this.props.moduleState.init({
            onSubmit: this.onSubmit
        });
    };

    /**
     * Updates the module state.
     */
    private readonly _updateModuleState = () => {
        this.props.moduleState.onReady();
    };

    /**
     * On submit.
     */
    private readonly onSubmit = (): void => {
        this._updateModuleState();
    };
}

export default Captcha;
