let PerformanceThresholdMs = 10000;
let Lookback = 10m;
Event
| where TimeGenerated > ago(Lookback)
| where EventLog == "Application"
| where EventID == 40102
| where Source == "Microsoft Dynamics - Store Commerce"
| where EventData has "ModelManagersRetailServerRequestFinished" or RenderedDescription has "ModelManagersRetailServerRequestFinished"
| extend DeviceName = Computer
| extend ParsedXml = parse_xml(EventData)
| extend EventDataXml = ParsedXml.DataItem.EventData
| extend DataNodes = EventDataXml.Data
| mv-expand DataNode = DataNodes
| extend DataValue = tostring(DataNode)
| summarize DataValues = make_list(DataValue), arg_max(TimeGenerated, *) by EventData
| extend
    PayloadText = trim_start("payload: ", tostring(DataValues[6])),
    Scope = tostring(DataValues[7])
| extend Payload = parse_json(PayloadText)
| extend
    ExecutionTimeInMs = toint(Payload.executionTimeInMs)
| where ExecutionTimeInMs > PerformanceThresholdMs
| distinct DeviceName